<%
image_name     = ENV.fetch('DISTRIB', 'jessie/8').split('/').first
debian_version = ENV.fetch('DISTRIB', 'jessie/8').split('/').last
%>
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: salt_solo
  formula: rkhunter

  # Install Salt from official repositories
  salt_install: apt
  salt_version: latest
  salt_apt_repo: 'http://repo.saltstack.com/apt/debian/<%= debian_version %>/amd64'
  salt_apt_repo_key: http://repo.saltstack.com/apt/debian/<%= debian_version %>/amd64/latest/SALTSTACK-GPG-KEY.pub

  # Don't install Chef
  require_chef: false

  # Configure Salt
  state_top:
    base:
      '*':
        - rkhunter.config

  pillars:
    top.sls:
      base:
        '*':
          - rkhunter
    rkhunter.sls:
      rkhunter:
        config:
          allow_ssh_root_user: 'yes'

platforms:
  - name: debian-<%= image_name %>
    driver_config:
      image: "debian:<%= image_name %>"
      platform: debian

verifier:
  name: inspec
  format: progress

suites:
  - name: rkhunter
    verifier:
      inspec_tests:
        - name: base
          path: test/integration/base
