language: ruby
sudo: required
cache: bundler
rvm:
  - 2.3.4
services:
  - docker
script:
  - bundle exec kitchen test
env:
  matrix:
    - DISTRIB=wheezy/7
    - DISTRIB=jessie/8
    - DISTRIB=stretch/9
